// Measures where the drawn body sits inside each character's art, and writes
// js/data/poses.js.
//
//   node tools/measure-poses.js
//
// Why this exists: every pose is a separate file, and the transparent margin
// around the character is different in each one. Two poses placed at the same
// box therefore do not put the character in the same place — which is what made
// a change of pose read as the character sliding sideways. With the margin
// measured, js/anchor.js can shift each layer so the body lands on the scene's
// anchor instead of the box doing.
//
// The numbers are fractions of the image, so they hold at any size and only
// need regenerating when the art itself changes.

const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DIRS = ["assets/images", "assets/game"];
// Bubble art is named after whoever is speaking through it, so it has to be
// excluded by name — it is not a character and must never be anchored.
// Page 3 of the story draws both characters as one picture, so scene_* counts
// too. Bubble art is named after whoever speaks through it, so it has to be
// excluded by name — it is not a character and must never be anchored.
const CAST = /^(?!bub)(?=.*(agni|neel|scene_))/i;
const S = 240; // sample grid; finer than this changes nothing past 3 decimals

function box(file) {
  const d = execFileSync("ffmpeg", ["-v", "error", "-i", file, "-vf", `scale=${S}:${S}`,
    "-pix_fmt", "rgba", "-f", "rawvideo", "-"], { maxBuffer: 1 << 26 });

  let x0 = S, x1 = -1, y0 = S, y1 = -1;
  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      // 40/255 rather than 0: the art has a faint anti-aliased halo that would
      // otherwise measure as several pixels of body.
      if (d[(y * S + x) * 4 + 3] > 40) {
        if (x < x0) x0 = x;
        if (x > x1) x1 = x;
        if (y < y0) y0 = y;
        if (y > y1) y1 = y;
      }
    }
  }
  if (x1 < 0) return null;
  const r = (v) => Math.round(v * 10000) / 10000;
  return [r(x0 / S), r((x1 + 1) / S), r(y0 / S), r((y1 + 1) / S)];
}

const found = [];
for (const dir of DIRS) {
  const abs = path.join(ROOT, dir);
  if (!fs.existsSync(abs)) continue;
  for (const f of fs.readdirSync(abs).sort()) {
    if (!/\.(webp|png)$/i.test(f) || !CAST.test(f)) continue;
    const b = box(path.join(abs, f));
    if (!b) continue;
    found.push([`${dir.split("/").pop()}/${f}`, b]);
    console.log(`  ${f.padEnd(24)} x ${b[0]}..${b[1]}   y ${b[2]}..${b[3]}`);
  }
}

const body = found.map(([k, b]) => `  "${k}": [${b.join(", ")}]`).join(",\n");
const out = `// Where the drawn body sits inside each character's art, as fractions of the
// image: [x0, x1, y0, y1].
//
// GENERATED by tools/measure-poses.js — do not edit by hand. Re-run it when a
// character's art changes.
//
// Every pose is a separate file with its own transparent margin, so two poses
// drawn at the same box do not put the character in the same place. js/anchor.js
// uses these to shift each layer instead, which is what keeps a change of pose
// from reading as the character sliding sideways.
export const POSE_BOX = {
${body}
};
`;
fs.writeFileSync(path.join(ROOT, "js/data/poses.js"), out);
console.log(`\nwrote js/data/poses.js — ${found.length} poses`);
