// Measures the FACE of every speech balloon and writes js/data/bubbles.js.
//
//   node tools/measure-bubbles.js
//
// Why this exists: a balloon is a round body plus a tail, and the tail is what
// makes "centre the text in the bubble" ambiguous. Centring inside the layer
// box puts the words off-centre, because the box has to be tall enough to
// contain the tail as well as the body — so the text sits high or low by
// however much the tail sticks out.
//
// The face is found by run length. For every row of the art, measure the
// widest run of opaque pixels: the body rows are wide, the tail rows are
// narrow. The face is the band of rows at least 55% as wide as the widest row,
// and its own left/right edges come from those rows only. Numbers are
// fractions of the image, so they hold at any size.
//
// The result is what js/game.js and js/story.js centre their text on.

const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DIRS = ["assets/game", "assets/images"];
const IS_BUBBLE = /^(bub|bubble)/i;
const S = 240;             // sample grid
const FACE_MIN = 0.55;     // a row this wide, relative to the widest, is body

function faceOf(file) {
  const d = execFileSync("ffmpeg", ["-v", "error", "-i", file, "-vf", `scale=${S}:${S}`,
    "-pix_fmt", "rgba", "-f", "rawvideo", "-"], { maxBuffer: 1 << 26 });

  // Widest opaque run per row, and where it starts.
  const rows = [];
  let widest = 0;
  for (let y = 0; y < S; y++) {
    let run = 0, start = 0, best = 0, bestAt = 0;
    for (let x = 0; x < S; x++) {
      if (d[(y * S + x) * 4 + 3] > 40) {
        if (run === 0) start = x;
        run++;
        if (run > best) { best = run; bestAt = start; }
      } else {
        run = 0;
      }
    }
    rows.push({ w: best, x0: bestAt, x1: bestAt + best });
    if (best > widest) widest = best;
  }

  // The longest unbroken band of body-width rows — the tail is thinner, and a
  // stray wide row elsewhere cannot drag the band with it.
  const wide = rows.map((r) => r.w >= widest * FACE_MIN);
  let bestRun = { from: 0, to: -1 };
  let from = -1;
  for (let y = 0; y <= S; y++) {
    if (wide[y] && from < 0) from = y;
    if ((!wide[y] || y === S) && from >= 0) {
      if (y - 1 - from > bestRun.to - bestRun.from) bestRun = { from, to: y - 1 };
      from = -1;
    }
  }

  let x0 = S, x1 = 0;
  for (let y = bestRun.from; y <= bestRun.to; y++) {
    x0 = Math.min(x0, rows[y].x0);
    x1 = Math.max(x1, rows[y].x1);
  }

  return {
    x0: +(x0 / S).toFixed(4),
    x1: +(x1 / S).toFixed(4),
    y0: +(bestRun.from / S).toFixed(4),
    y1: +((bestRun.to + 1) / S).toFixed(4)
  };
}

const out = {};
for (const dir of DIRS) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) continue;
  for (const name of fs.readdirSync(full).sort()) {
    if (!/\.(webp|png)$/i.test(name)) continue;
    if (!IS_BUBBLE.test(name)) continue;
    const key = `${dir.split("/").pop()}/${name}`;
    const f = faceOf(path.join(full, name));
    out[key] = [f.x0, f.x1, f.y0, f.y1];
    console.log(`  ${name.padEnd(24)} face x ${f.x0}..${f.x1}   y ${f.y0}..${f.y1}`);
  }
}

const body = Object.entries(out)
  .map(([k, v]) => `  "${k}": [${v.join(", ")}]`)
  .join(",\n");

fs.writeFileSync(path.join(ROOT, "js/data/bubbles.js"),
`// Where the round FACE of each speech balloon sits inside its image, as
// fractions: [x0, x1, y0, y1].
//
// GENERATED by tools/measure-bubbles.js — do not edit by hand. Re-run it when
// a balloon's art changes.
//
// A balloon is a body plus a tail. Centring text in the layer box therefore
// does NOT centre it in the balloon: the box is sized to hold the tail too, so
// the words drift towards whichever side the tail is not on. These numbers are
// the body alone, so js/game.js and js/story.js can put a line in the middle of
// the thing the reader actually sees.
export const BUBBLE_FACE = {
${body}
};

// The face of a balloon whose art has been mirrored (the tail is flipped to
// point at whoever is speaking), in the same fractions.
export function faceOf(src, mirrored = false) {
  const file = src.split("/").slice(-2).join("/");
  const box = BUBBLE_FACE[file];
  if (!box) return null;
  const [x0, x1, y0, y1] = box;
  return mirrored ? [1 - x1, 1 - x0, y0, y1] : box;
}
`);

console.log(`\nwrote js/data/bubbles.js — ${Object.keys(out).length} balloons`);
